export const users = [
  {
    Login: 'zra',
    FullName: 'Зинатуллина Резеда Айратовна',
    SupplierID: 1,
    CategoryID: 1,
    QuantityPerUnit: '10 boxes x 20 bags',
    Roles: 'Руководитель, Администратор',
    UnitsInStock: 39,
    UnitsOnOrder: 0,
    ReorderLevel: 10,
    Locked: false,
    Email: 'ZinatullinaRA@tatenergo.ru',
    Description: 'Soft drinks, coffees, teas, beers, and ales',
    FirstOrderedOn: new Date(1996, 8, 20)
  },
  {
    Login: 'uvip',
    FullName: 'Уразаева Виолетта Пулатовна ',
    SupplierID: 1,
    CategoryID: 1,
    QuantityPerUnit: '24 - 12 oz bottles',
    Roles: 'Руководитель',
    UnitsInStock: 17,
    UnitsOnOrder: 40,
    ReorderLevel: 25,
    Locked: false,
    Email: 'UrazaevaVP@tatenergo.ru',
    Description: 'Soft drinks, coffees, teas, beers, and ales',
    FirstOrderedOn: new Date(1996, 7, 12)
  },
  {
    Login: 'kav',
    FullName: 'Клементьев Андрей Валерьевич',
    SupplierID: 1,
    CategoryID: 2,
    QuantityPerUnit: '12 - 550 ml bottles',
    Roles: 'Руководитель',
    UnitsInStock: 13,
    UnitsOnOrder: 70,
    ReorderLevel: 25,
    Locked: false,
    Email: 'KlementievAV@tatenergo.ru',
    Description: 'Sweet and savory sauces, relishes, spreads, and seasonings',
    FirstOrderedOn: new Date(1996, 8, 26)
  },
  {
    Login: 'axm',
    FullName: 'Хакимзянов Айдар Магсумянович',
    SupplierID: 2,
    CategoryID: 2,
    QuantityPerUnit: '48 - 6 oz jars',
    Roles: 'Инспектор',
    UnitsInStock: 53,
    UnitsOnOrder: 0,
    ReorderLevel: 0,
    Locked: false,
    Email: 'ahakimzyanov@tatenergo.ru',
    Description: 'Sweet and savory sauces, relishes, spreads, and seasonings',
    FirstOrderedOn: new Date(1996, 9, 19)
  },
  {
    Login: 'atol',
    FullName: 'Толмачев Андрей Викторович',
    SupplierID: 2,
    CategoryID: 2,
    QuantityPerUnit: '36 boxes',
    Roles: 'Руководитель, Инспектор',
    UnitsInStock: 0,
    UnitsOnOrder: 0,
    ReorderLevel: 0,
    Locked: true,
    Email: 'atolmachev@tatenergo.ru',
    Description: 'Sweet and savory sauces, relishes, spreads, and seasonings',
    FirstOrderedOn: new Date(1996, 7, 17)
  },
  {
    Login: 'sgul',
    FullName: 'Сагинбаева Гульшат Магсумовна',
    SupplierID: 3,
    CategoryID: 2,
    QuantityPerUnit: '12 - 8 oz jars',
    Roles: 'Инспектор',
    UnitsInStock: 120,
    UnitsOnOrder: 0,
    ReorderLevel: 25,
    Locked: false,
    Email: 'gsaginbaeva@tatenergo.ru',
    Description: 'Sweet and savory sauces, relishes, spreads, and seasonings',
    FirstOrderedOn: new Date(1996, 9, 19)
  },
  {
    Login: 'ifro',
    FullName: 'Фролов Игорь Сергеевич',
    SupplierID: 3,
    CategoryID: 7,
    QuantityPerUnit: '12 - 1 lb pkgs.',
    Roles: 'Инспектор',
    UnitsInStock: 15,
    UnitsOnOrder: 0,
    ReorderLevel: 10,
    Locked: false,
    Email: 'ifrolov@tatenergo.ru',
    Description: 'Dried fruit and bean curd',
    FirstOrderedOn: new Date(1996, 7, 22)
  },
  {
    Login: 'apol',
    FullName: 'Полищук Арина Сергеевна',
    SupplierID: 3,
    CategoryID: 2,
    QuantityPerUnit: '12 - 12 oz jars',
    Roles: 'Инспектор',
    UnitsInStock: 6,
    UnitsOnOrder: 0,
    ReorderLevel: 0,
    Locked: false,
    Email: 'apolischuk@tatenergo.ru',
    Description: 'Sweet and savory sauces, relishes, spreads, and seasonings',
    FirstOrderedOn: new Date(1996, 11, 1)
  },
  {
    Login: 'sdon',
    FullName: 'Донцев Семен Сергеевич',
    SupplierID: 4,
    CategoryID: 6,
    QuantityPerUnit: '18 - 500 g pkgs.',
    Roles: 'Инспектор',
    UnitsInStock: 29,
    UnitsOnOrder: 0,
    ReorderLevel: 0,
    Locked: true,
    Email: 'sdoncev@tatenergo.ru',
    Description: 'Prepared meats',
    FirstOrderedOn: new Date(1997, 1, 21)
  },
  {
    Login: 'agdav',
    FullName: 'Агдавлетов Айдар Айратович',
    SupplierID: 4,
    CategoryID: 8,
    QuantityPerUnit: '12 - 200 ml jars',
    Roles: 'Инспектор',
    UnitsInStock: 31,
    UnitsOnOrder: 0,
    ReorderLevel: 0,
    Locked: false,
    Email: 'aagdavletov@tatenergo.ru',
    Description: 'Seaweed and fish',
    FirstOrderedOn: new Date(1996, 8, 5)
  }
];
